# GDDR 메모리 파라미터 제너레이터
# Virtuoso Parametric GDDR Cell / I/O Generator
# GDDR 세대별 셀 어레이 및 고속 I/O 회로 설계를 위한 파라미터 및 SKILL 코드 생성

import json
from dataclasses import dataclass, field, asdict
from typing import List, Dict
from pathlib import Path
from enum import Enum


class SignallingType(Enum):
    """시그널링 타입"""
    NRZ = "nrz"            # 2-Level (GDDR5/GDDR6)
    PAM4 = "pam4"          # 4-Level (GDDR6X)
    PAM3 = "pam3"          # 3-Level (연구)


class ChannelType(Enum):
    """채널 구조 타입"""
    SINGLE_32BIT = "single_32bit"      # 단일 32-bit (GDDR5)
    DUAL_16BIT = "dual_16bit"          # 듀얼 16-bit 서브채널 (GDDR6)
    DUAL_16BIT_PAM4 = "dual_16bit_pam4" # 듀얼 + PAM4 (GDDR6X)


@dataclass
class TechnologyNode:
    """기술 노드 정의"""
    name: str
    node_nm: int
    gate_length: float  # nm
    min_pitch: float    # nm
    vdd: float          # V (core)
    vddq: float         # V (I/O 전원)
    vth: float          # V
    oxide_thickness: float  # nm


@dataclass
class GDDRConfig:
    """GDDR 세대 설계 파라미터"""
    generation: str
    tech_node: TechnologyNode
    signalling: SignallingType
    channel_type: ChannelType
    # I/O 파라미터
    data_rate_per_pin: float    # Gbps
    eye_margin: float           # mV (아이 다이어그램 마진)
    tx_swing: float             # V (출력 스윙)
    # 채널 파라미터
    bus_width: int              # 비트
    channels: int               # 독립 채널 수
    subchannels: List[int]      # 서브채널 구성
    # 대역폭
    bandwidth: float            # GB/s
    # 셀 어레이
    num_banks: int
    bank_groups: int
    # 패키징
    package: str
    pins: int
    # 특징
    features: List[str] = field(default_factory=list)


# ============================================================
# GDDR 세대별 노드 정의
# ============================================================

GDDR_CONFIGS = {
    "GDDR5": GDDRConfig(
        generation="GDDR5",
        tech_node=TechnologyNode(
            name="GDDR5 70nm", node_nm=70, gate_length=70,
            min_pitch=90, vdd=1.5, vddq=1.5, vth=0.4, oxide_thickness=3.0
        ),
        signalling=SignallingType.NRZ,
        channel_type=ChannelType.SINGLE_32BIT,
        data_rate_per_pin=6.0, eye_margin=150, tx_swing=0.8,
        bus_width=32, channels=1, subchannels=[32],
        bandwidth=192, num_banks=16, bank_groups=4,
        package="BGA (170-ball)", pins=170,
        features=["WCK/CK 분리 클럭", "8n-prefetch", "Pseudo-QDR", "EDC"]
    ),
    "GDDR6": GDDRConfig(
        generation="GDDR6",
        tech_node=TechnologyNode(
            name="GDDR6 12nm", node_nm=12, gate_length=12,
            min_pitch=24, vdd=1.25, vddq=1.35, vth=0.25, oxide_thickness=1.2
        ),
        signalling=SignallingType.NRZ,
        channel_type=ChannelType.DUAL_16BIT,
        data_rate_per_pin=16.0, eye_margin=100, tx_swing=0.6,
        bus_width=32, channels=2, subchannels=[16, 16],
        bandwidth=672, num_banks=16, bank_groups=4,
        package="BGA (180-ball)", pins=180,
        features=["Dual 16-bit 서브채널", "16n-prefetch", "Deep BCAT", "저전력 모드"]
    ),
    "GDDR6X": GDDRConfig(
        generation="GDDR6X",
        tech_node=TechnologyNode(
            name="GDDR6X 9nm", node_nm=9, gate_length=9,
            min_pitch=20, vdd=1.2, vddq=1.35, vth=0.2, oxide_thickness=1.0
        ),
        signalling=SignallingType.PAM4,
        channel_type=ChannelType.DUAL_16BIT_PAM4,
        data_rate_per_pin=21.0, eye_margin=70, tx_swing=0.5,
        bus_width=32, channels=2, subchannels=[16, 16],
        bandwidth=1000, num_banks=16, bank_groups=4,
        package="BGA (180-ball)", pins=180,
        features=["PAM4 시그널링", "노이즈 억제 설계", "EUV-BCAT", "1TB/s+"]
    ),
}


# ============================================================
# SKILL 코드 생성
# ============================================================

def skill_header(lib: str, cell: str, view: str = "layout") -> str:
    return f"""; ============================================================
; GDDR Memory Generator
; Library: {lib}
; Cell:    {cell}
; View:    {view}
; Auto-generated by GDDR Design Automation Tool
; ============================================================

procedure(gddrCreate{cell}()
    let((cv ws tech
          chipW chipH
          chSel chOffset
          i))
"""


def generate_channel_layout(gen_name: str, config: GDDRConfig, lib: str = "gddr_lib") -> str:
    """GDDR Channel 어레이 배치 및 라우팅 SKILL 생성"""
    cell_name = f"gddr_{gen_name.lower()}_array"

    skill = skill_header(lib, cell_name)

    # 칩 대략 치수 (채널당)
    if config.channel_type == ChannelType.SINGLE_32BIT:
        chipW, chipH = 14.0, 8.0   # mm (단일 채널)
    else:
        chipW, chipH = 16.0, 9.0   # mm (듀얼 채널)

    skill += f"""
        ; ========================================
        ; {gen_name} - {config.tech_node.name}
        ; ========================================
        ; 채널 구조: {config.channel_type.value}
        ; 시그널링: {config.signalling.value}
        ; 데이터 레이트: {config.data_rate_per_pin} Gbps/pin
        ; 대역폭: {config.bandwidth} GB/s
        ; I/O 전원: VDDQ = {config.tech_node.vddq}V
        ; 칩 크기: {chipW}mm x {chipH}mm
        ; 패키징: {config.package}

        ; 체널 / 뱅크 그룹 분할
        ; ┌─────────────────────────────┐
        ; │   BankGroup 0   BankGroup 1 │
        ; │   ┌─────┐      ┌─────┐      │
        ; │   │  0  │      │  2  │      │
        ; │   └─────┘      └─────┘      │
        ; │   ┌─────┐      ┌─────┐      │
        ; │   │  1  │      │  3  │      │
        ; │   └─────┘      └─────┘      │
        ; └─────────────┴─────────────┘

        ; 뱅크 그룹 수: {config.bank_groups}
        ; 뱅크 수: {config.num_banks}
        ; 채널 수: {config.channels}
    """

    # 채널 배치
    skill += f"""
        ; 채널 A 배치 (좌측)
        chOffset = 0.0
        for(i 0 ({config.channels}-1)
            dbCreateRect(cv list("M1" "drawing")
                list(chOffset 0.0 (+ chOffset {chipW/2}) {chipH})
            )
            dbCreateText(cv sprintf(nil "Channel_%c" (+ 65 i))
                list(+ chOffset 0.5) 1.0
                "M1" 0.5 "centerCenter")
            chOffset = chOffset + {chipW/2} + 0.5   ; 채널 간 간격
        )

        ; 뱅크 그룹 배치
        bgWidth = {chipW/2} / {config.bank_groups}
        for(i 0 ({config.bank_groups}-1)
            dbCreateText(cv sprintf(nil "BankGroup_%d" i)
                list(+ (* bgWidth i) 1.0) {chipH - 1.0}
                "M2" 0.3 "centerCenter")
        )

        ; 데이터 핀 배치 (DQS 영역)
        dbCreateText(cv "DQS"
            list(1.0 {chipH - 3.0}) "M3" 0.3 "centerCenter")
        dbCreateText(cv "WCLK"
            list(3.0 {chipH - 3.0}) "M3" 0.3 "centerCenter")
        dbCreateText(cv "CK/CK#"
            list(5.0 {chipH - 3.0}) "M3" 0.3 "centerCenter")
    """

    skill += """
        when(cv,
            dbSave(cv)
            println("GDDR array layout generated")
        )
    )
endprocedure
"""
    return skill


def generate_io_driver(gen_name: str, config: GDDRConfig, lib: str = "gddr_lib") -> str:
    """GDDR I/O Driver 회로 생성 (PAM4 포함)"""
    cell_name = f"gddr_{gen_name.lower()}_io_driver"

    skill = skill_header(lib, cell_name)

    if config.signalling == SignallingType.PAM4:
        # PAM4 송신기 회로
        skill += f"""
        ; ========================================
        ; {gen_name} PAM4 TX Driver
        ; ========================================

        ; PAM4 레벨: 00, 01, 10, 11 (4 levels)
        ; 눈(Eye) 마진: {config.eye_margin}mV (레벨 간격)
        ; 출력 스윙: {config.tx_swing}V

        ; ── PAM4 Transmitter 회로 구성 ──
        ;   MSB ──> [Upper Driver] ─┐
        ;                            ├──> TX_OUT (4레벨 출력)
        ;   LSB ──> [Lower Driver] ─┘
        ;
        ;   00 = V00 (0V)
        ;   01 = V01 (Vswing/3)
        ;   10 = V10 (2*Vswing/3)
        ;   11 = V11 (Vswing)

        ; MSB/LSB 디코더
        dbCreateInst(cv "pam4_encoder" "PAM4_ENC" list(2.0 8.0) "R0")
        dbCreateInst(cv "driver_hi" "DRV_HI" list(4.0 6.0) "R0")
        dbCreateInst(cv "driver_lo" "DRV_LO" list(4.0 4.0) "R0")
        dbCreateInst(cv "tx_pad" "TX_PAD" list(6.0 5.0) "R0")

        ; 신호 배선 (이상적 라벨 연결)
        dbCreateText(cv "MSB" list(1.0 8.0) "M1" 0.2 "centerCenter")
        dbCreateText(cv "LSB" list(1.0 7.0) "M1" 0.2 "centerCenter")
        dbCreateText(cv "TX_OUT" list(7.0 5.0) "M2" 0.2 "centerCenter")
        dbCreateText(cv "VDDQ" list(3.0 9.0) "M1" 0.2 "centerCenter")

        ; PAM4 레벨 레퍼런스
        dbCreateText(cv "VREF1" list(8.0 9.0) "M3" 0.1 "centerCenter")
        dbCreateText(cv "VREF2" list(8.0 8.0) "M3" 0.1 "centerCenter")
        dbCreateText(cv "VREF3" list(8.0 7.0) "M3" 0.1 "centerCenter")
        """

    else:
        # NRZ (GDDR5/GDDR6) 송신기
        skill += f"""
        ; ========================================
        ; {gen_name} NRZ TX Driver
        ; ========================================

        ; NRZ 레벨: 0, 1 (2 levels)
        ; 눈 마진: {config.eye_margin}mV
        ; 출력 스윙: {config.tx_swing}V

        ; ── NRZ Transmitter 회로 구성 ──
        ;   DATA ──> [Driver] ──> TX_OUT (2레벨 출력)
        ;
        ;   0 = V00 (0V)
        ;   1 = V11 (Vswing)

        dbCreateInst(cv "driver" "DRV" list(3.0 6.0) "R0")
        dbCreateInst(cv "tx_pad" "TX_PAD" list(5.0 6.0) "R0")

        dbCreateText(cv "DATA" list(1.0 6.0) "M1" 0.2 "centerCenter")
        dbCreateText(cv "TX_OUT" list(6.0 6.0) "M2" 0.2 "centerCenter")
        dbCreateText(cv "VDDQ" list(3.0 7.0) "M1" 0.2 "centerCenter")
        """

    skill += """
        ; WCK 차동 데이터 클럭 수신
        dbCreateInst(cv "wck_receiver" "WCK_RX" list(2.0 2.0) "R0")
        dbCreateText(cv "WCK" list(1.0 2.0) "M3" 0.2 "centerCenter")
        dbCreateText(cv "WCK#" list(1.0 1.0) "M3" 0.2 "centerCenter")

        when(cv,
            dbSave(cv)
            println("GDDR I/O driver generated")
        )
    )
endprocedure
"""
    return skill


def generate_pam4_encoder(lib: str = "gddr_lib") -> str:
    """PAM4 인코더 회로 SKILL"""
    return f"""; ============================================================
; PAM4 Encoder for GDDR6X
; 2-bit (MSB/LSB) → PAM4 레벨 변환
; ============================================================

procedure(gddrPAM4Encode(
    vref1       ; 하한 레퍼런스
    vref2       ; 중앙 레퍼런스
    vref3       ; 상한 레퍼런스
)
    let((cv schema)

        ; 스케마틱 생성
        schema = dbOpenCellViewByType("gddr_lib" "pam4_encoder" "schematic" "" "a")

        ; 논리 테이블:
        ; MSB LSB → 출력 전압
        ;  0   0  → V00 = VSS
        ;  0   1  → V01 = Vswing/3
        ;  1   0  → V10 = 2*Vswing/3
        ;  1   1  → V11 = Vswing

        ; DAC(2-bit) 구현
        ; MSB: 상위 비트 가중치 (2/3 스윙)
        ; LSB: 하위 비트 가중치 (1/3 스윙)

        dbSave(schema)
        printf("PAM4 Encoder generated\\n")
    )
endprocedure
"""


def generate_python_config() -> str:
    """GDDR 설정 JSON 생성"""
    configs = []
    for gen, cfg in GDDR_CONFIGS.items():
        configs.append({
            "generation": cfg.generation,
            "tech": cfg.tech_node.name,
            "node_nm": cfg.tech_node.node_nm,
            "vdd_V": cfg.tech_node.vdd,
            "vddq_V": cfg.tech_node.vddq,
            "signalling": cfg.signalling.value,
            "channel_type": cfg.channel_type.value,
            "data_rate_Gbps_per_pin": cfg.data_rate_per_pin,
            "eye_margin_mV": cfg.eye_margin,
            "tx_swing_V": cfg.tx_swing,
            "bus_width_bit": cfg.bus_width,
            "channels": cfg.channels,
            "subchannels": cfg.subchannels,
            "bandwidth_GB_s": cfg.bandwidth,
            "num_banks": cfg.num_banks,
            "bank_groups": cfg.bank_groups,
            "package": cfg.package,
            "pins": cfg.pins,
            "features": cfg.features,
        })
    return json.dumps(configs, indent=2, ensure_ascii=False)


def main():
    output_dir = Path(__file__).parent / "generated"
    output_dir.mkdir(exist_ok=True)

    print("=" * 60)
    print("GDDR Memory Design Automation Tool")
    print("=" * 60)

    for gen_name, config in GDDR_CONFIGS.items():
        print(f"\n[{gen_name}] Generating...")

        # 채널 어레이 레이아웃
        skill = generate_channel_layout(gen_name, config)
        fname = f"gddr_{gen_name.lower()}_array.skill"
        (output_dir / fname).write_text(skill, encoding='utf-8')
        print(f"  Generated: {fname}")

        # I/O 드라이버 회로
        skill = generate_io_driver(gen_name, config)
        fname = f"gddr_{gen_name.lower()}_io_driver.skill"
        (output_dir / fname).write_text(skill, encoding='utf-8')
        print(f"  Generated: {fname}")

        # 클럭 트리 생성 코드
        skill = generate_channel_layout  # reuse structure for clock tree below
        print(f"  Data rate: {config.data_rate_per_pin} Gbps/pin, "
              f"BW: {config.bandwidth} GB/s")

    # PAM4 인코더
    print("\n[Common] Generating PAM4 Encoder...")
    (output_dir / "pam4_encoder.skill").write_text(
        generate_pam4_encoder(), encoding='utf-8')
    print("  Generated: pam4_encoder.skill")

    # 설정 JSON
    print("\n[Common] Generating Config JSON...")
    (output_dir / "gddr_configs.json").write_text(
        generate_python_config(), encoding='utf-8')
    print("  Generated: gddr_configs.json")

    print("\n" + "=" * 60)
    print(f"All files in: {output_dir}")
    print("=" * 60)

    # 요약
    print("\n[Summary]")
    print("-" * 95)
    print(f"{'Gen':<10} {'Tech':<12} {'Sig':<8} {'Rate(Gbps)':<12} {'BW(GB/s)':<10} {'Pkg':<20}")
    print("-" * 95)
    for gen, cfg in GDDR_CONFIGS.items():
        print(f"{gen:<10} {cfg.tech_node.name:<12} {cfg.signalling.value:<8} "
              f"{cfg.data_rate_per_pin:<12} {cfg.bandwidth:<10} {cfg.package:<20}")
    print("-" * 95)


if __name__ == "__main__":
    main()
